services:
  mockServer:
    image: mockserver/mockserver:latest
    command: -serverPort 8000
    ports:
      - 8000:8000
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /mock/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mock/backend.json
    volumes:
      - ../mock:/mock
    network_mode: host

  frontend:
    build:
      context: ../../frontend
    ports:
      - "5173:5173"
    network_mode: host
