services:
  backend:
    build:
      context: ../../backend
      args:
        app_args:
    environment:
      LOG_LEVEL: ERROR
    ports:
      - "8000:8000"
    volumes:
      - ../../backend/db:/backend/db
    network_mode: host

  frontend:
    build:
      context: ../../frontend
    ports:
      - "5173:5173"
    network_mode: host
